{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.fullname" . }}-nginx-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  default.conf: |
    {{- .Values.configmap.nginxConfig | nindent 4 }}
{{- end }}
